[package]
name = "day12"
version = "0.1.0"
authors = ["Brian Yeung <brianyeung2011@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempdir = "0.3"